#################PING
GET https://{{host}}/ping
Content-Type: application/json

#################CREATE PARTIAL DECK
#####IN THE PROBLEM STATEMENT CARDS WAS PASSED IN QUERY PARAM, BUT SINCE I WAS ACCEPTING FIELDS LIKE SHUFFLE AND PARTIAL SO I MOVED IT TO REQUEST BODY
POST https://{{host}}/decks
Content-Type: application/json

{
  "shuffle": false,
  "partial": true,
  "cards": [
    "8S",
    "5S"
  ]
}

#################CREATE IMPARTIAL SHUFFLED DECK
POST https://{{host}}/decks
Content-Type: application/json

{
  "shuffle": true
}

#################CREATE DEFAULT DECK
POST https://{{host}}/decks
Content-Type: application/json

{
}

########GET A DECK ===> Open a Deck
GET https://{{host}}/decks/c3d86303-8684-661e-1efd-58410a8860e7
Content-Type: application/json

########DRAW CARD(S)
PATCH https://{{host}}/decks/c3d86303-8684-661e-1efd-58410a8860e7?count=9
Content-Type: application/json