#################PING
GET https://{{host}}/ping
Content-Type: application/json

#################CREATE PARTIAL DECK
#####IN THE PROBLEM STATEMENT CARDS WAS PASSED IN QUERY PARAM, BUT SINCE I WAS ACCEPTING FIELDS LIKE SHUFFLE AND PARTIAL SO I MOVED IT TO REQUEST BODY
POST https://{{host}}/decks
Content-Type: application/json

{
  "shuffle": false,
  "partial": true,
  "cards": [
    "8S",
    "5S"
  ]
}

#################CREATE IMPARTIAL SHUFFLED DECK
POST https://{{host}}/decks
Content-Type: application/json

{
  "shuffle": true
}

#################CREATE DEFAULT DECK
POST https://{{host}}/decks
Content-Type: application/json

{
}

########GET A DECK ===> Open a Deck
GET https://{{host}}/decks/c0b3b523-2724-c6c3-49af-18c4cee70e31
Content-Type: application/json

########DRAW CARD(S)
PATCH https://{{host}}/decks/c0b3b523-2724-c6c3-49af-18c4cee70e31?count=9
Content-Type: application/json